### ISSUE TITLE
Potentially missing library?

### ISSUE THREAD

**Issue by IngwiePhoenix** [nuive/pokemon-access#4]
Hello!

A friend who is a little less tech-savy than I, wanted to set this up. However, he got this error message:

![image](https://user-images.githubusercontent.com/2893716/183269021-b90fc5dc-a521-4d27-8706-59dc5394921d.png)

Looking at the highlighted line, it seems that the FFI call does not work; so `libInputBox.dll` or `inputbox.dll` is missing. Where is this supposed to be found and where would I have to place it - or, he - to make it work?

Thanks!

**Comment by nuive** [comment]
In this repository you'll only find the source code. You'll need the complete package, look here:
https://forum.audiogames.net/topic/37774/pokemon-access/
